import { ModelCapabilities, ModelKind } from './types';

type RegistryEntry = {
  kind?: ModelKind;
  capabilities?: ModelCapabilities;
};

/**
 * Hardcoded model capability registry.
 * Covers well-known models from major providers.
 * Key: lowercase model ID (exact match or with suffix stripping).
 */
const REGISTRY: Record<string, RegistryEntry> = {
  // ── OpenAI ──────────────────────────────────────────
  'gpt-5.4': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gpt-5.4-pro': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gpt-5.4-mini': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gpt-5.4-nano': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'gpt-5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'gpt-5-mini': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-5-nano': { kind: 'chat' },
  'gpt-4.1': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4.1-mini': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4.1-nano': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4o': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4o-mini': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4-turbo': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gpt-4': { kind: 'chat', capabilities: { tools: true } },
  'gpt-4.5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'gpt-4.5-mini': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'chatgpt-4o-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'o1': { kind: 'chat', capabilities: { reasoning: true } },
  'o1-pro': { kind: 'chat', capabilities: { reasoning: true } },
  'o1-mini': { kind: 'chat', capabilities: { reasoning: true } },
  'o3': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'o3-pro': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'o3-mini': { kind: 'chat', capabilities: { reasoning: true, tools: true } },
  'o4-mini': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gpt-image-1.5': { kind: 'image' },
  'gpt-image-1': { kind: 'image' },
  'gpt-image-1-mini': { kind: 'image' },
  'dall-e-3': { kind: 'image' },
  'dall-e-2': { kind: 'image' },
  'gpt-realtime-1.5': { kind: 'audio' },
  'gpt-realtime': { kind: 'audio' },
  'gpt-realtime-mini': { kind: 'audio' },
  'gpt-audio-1.5': { kind: 'audio' },
  'gpt-audio': { kind: 'audio' },
  'gpt-audio-mini': { kind: 'audio' },
  'gpt-4o-transcribe': { kind: 'audio' },
  'gpt-4o-mini-transcribe': { kind: 'audio' },
  'gpt-4o-mini-tts': { kind: 'audio' },
  'tts-1': { kind: 'audio' },
  'tts-1-hd': { kind: 'audio' },
  'whisper-1': { kind: 'audio' },
  'text-embedding-3-large': { kind: 'embedding' },
  'text-embedding-3-small': { kind: 'embedding' },
  'text-embedding-ada-002': { kind: 'embedding' },

  // ── Anthropic ───────────────────────────────────────
  'claude-opus-4-6': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'claude-sonnet-4-6': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'claude-haiku-4-5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'claude-sonnet-4-5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'claude-opus-4-5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'claude-opus-4-1': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'claude-sonnet-4': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'claude-opus-4': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'claude-haiku-4': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'claude-3-opus-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'claude-3-sonnet-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'claude-3-haiku-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'claude-3.5-sonnet-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'claude-3.5-haiku-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },

  // ── Google Gemini ───────────────────────────────────
  'gemini-3.1-pro-preview': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-3-flash-preview': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-3-pro-preview': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-2.5-pro': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-2.5-flash': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-2.5-flash-lite': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'gemini-2.0-flash': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gemini-2.0-flash-lite': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gemini-1.5-pro': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gemini-1.5-flash': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'gemini-3.1-flash-image-preview': { kind: 'image', capabilities: { vision: true } },
  'gemini-3-pro-image': { kind: 'image', capabilities: { vision: true } },
  'gemini-2.5-flash-image': { kind: 'image', capabilities: { vision: true } },
  'imagen-4.0-generate': { kind: 'image' },
  'imagen-4.0-generate-fast': { kind: 'image' },
  'imagen-4.0-generate-ultra-fast': { kind: 'image' },
  'imagen-3.0-generate-002': { kind: 'image' },
  'veo-3.1': { kind: 'video' },
  'veo-3.1-fast': { kind: 'video' },
  'veo-3.1-lite': { kind: 'video' },
  'veo-3': { kind: 'video' },
  'gemini-embedding-001': { kind: 'embedding' },
  'gemini-embedding-2': { kind: 'embedding' },
  'text-embedding-005': { kind: 'embedding' },
  'text-embedding-004': { kind: 'embedding' },

  // ── DeepSeek ────────────────────────────────────────
  'deepseek-chat': { kind: 'chat', capabilities: { tools: true } },
  'deepseek-reasoner': { kind: 'chat', capabilities: { reasoning: true } },
  'deepseek-r1': { kind: 'chat', capabilities: { reasoning: true } },
  'deepseek-v4': { kind: 'chat', capabilities: { tools: true } },
  'deepseek-v3': { kind: 'chat', capabilities: { tools: true } },

  // ── Qwen ────────────────────────────────────────────
  'qwen3-max': { kind: 'chat', capabilities: { tools: true, reasoning: true, webSearch: true } },
  'qwen3.6-plus': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'qwen3.5-plus': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'qwen-plus': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'qwen-turbo': { kind: 'chat', capabilities: { tools: true } },
  'qwen-long': { kind: 'chat', capabilities: { tools: true } },
  'qwen-max': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen-vl-max': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen-vl-plus': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen3-vl-max': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'qwq-plus': { kind: 'chat', capabilities: { reasoning: true, tools: true } },
  'qwq-32b': { kind: 'chat', capabilities: { reasoning: true, tools: true } },
  'qwen3-235b-a22b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen3-32b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'text-embedding-v3': { kind: 'embedding' },

  // ── GLM / 智谱 ──────────────────────────────────────
  // Text models
  'glm-5.1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-5': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-5-turbo': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-4.7': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-4.7-flashx': { kind: 'chat', capabilities: { tools: true } },
  'glm-4.7-flash': { kind: 'chat', capabilities: { tools: true } },
  'glm-4.6': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-4.5': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'glm-4.5-air': { kind: 'chat', capabilities: { tools: true } },
  'glm-4.5-airx': { kind: 'chat', capabilities: { tools: true } },
  'glm-4.5-flash': { kind: 'chat', capabilities: { tools: true } },
  'glm-4-flashx-250414': { kind: 'chat', capabilities: { tools: true } },
  'glm-4-plus': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'glm-4': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'glm-4-0520': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'glm-4-long': { kind: 'chat', capabilities: { tools: true } },
  'glm-zero-preview': { kind: 'chat', capabilities: { reasoning: true } },
  // Vision models
  'glm-5v-turbo': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'glm-4.6v': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'glm-4.6v-flash': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'glm-4.5v': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'glm-4.1v-thinking': { kind: 'chat', capabilities: { vision: true, reasoning: true } },
  'glm-4.1v-thinking-flashx': { kind: 'chat', capabilities: { vision: true, reasoning: true } },
  'glm-4.1v-thinking-flash': { kind: 'chat', capabilities: { vision: true, reasoning: true } },
  'glm-4v': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'glm-4v-plus': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'glm-4v-flash': { kind: 'chat', capabilities: { vision: true } },
  'glm-ocr': { kind: 'chat', capabilities: { vision: true } },
  'autoglm-phone': { kind: 'chat', capabilities: { vision: true, tools: true } },
  // Z1 series (deprecated 2025.11.15, kept for compatibility)
  'glm-z1-air': { kind: 'chat', capabilities: { reasoning: true } },
  'glm-z1-airx': { kind: 'chat', capabilities: { reasoning: true } },
  'glm-z1-flash': { kind: 'chat', capabilities: { reasoning: true } },
  // Other chat models
  'charglm-4': { kind: 'chat' },
  'emohaa': { kind: 'chat' },
  'codegeex-4': { kind: 'chat', capabilities: { tools: true } },
  // Image generation
  'glm-image': { kind: 'image' },
  'cogview-4': { kind: 'image' },
  'cogview-3-flash': { kind: 'image' },
  // Video generation
  'cogvideox-3': { kind: 'video' },
  'cogvideox-flash': { kind: 'video' },
  'cogvideox': { kind: 'video' },
  'vidu-2': { kind: 'video' },
  'vidu-q1': { kind: 'video' },
  // Audio
  'glm-tts': { kind: 'audio' },
  'glm-tts-clone': { kind: 'audio' },
  'glm-asr-2512': { kind: 'audio' },
  'glm-realtime': { kind: 'audio' },
  'glm-4-voice': { kind: 'audio' },
  // Embedding
  'embedding-3': { kind: 'embedding' },
  'embedding-2': { kind: 'embedding' },

  // ── Grok / xAI ──────────────────────────────────────
  'grok-4.20-0309-reasoning': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'grok-4.20-0309-non-reasoning': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'grok-4.20-multi-agent-0309': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'grok-4-1-fast-reasoning': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'grok-4-1-fast-non-reasoning': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'grok-3': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'grok-3-mini': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'grok-4': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'grok-imagine-image-pro': { kind: 'image' },
  'grok-imagine-image': { kind: 'image' },
  'grok-imagine-image-lite': { kind: 'image' },
  'grok-imagine-video': { kind: 'video' },

  // ── Doubao / 豆包 ──────────────────────────────────
  'doubao-seed-2.0-pro': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'doubao-seed-2.0-lite': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true, webSearch: true } },
  'doubao-seed-2.0-mini': { kind: 'chat', capabilities: { tools: true } },
  'doubao-seed-2.0-code': { kind: 'chat', capabilities: { tools: true } },
  'doubao-seed-1.8': { kind: 'chat', capabilities: { tools: true } },
  'doubao-seed-1.6': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'doubao-seed-1.5': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'doubao-1.5-pro': { kind: 'chat', capabilities: { tools: true } },

  // ── MiniMax ─────────────────────────────────────────
  'minimax-m2.7': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'minimax-m2.7-highspeed': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'minimax-m2.5': { kind: 'chat', capabilities: { tools: true } },
  'minimax-m2.5-highspeed': { kind: 'chat', capabilities: { tools: true } },
  'minimax-m2.1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'minimax-m2.1-highspeed': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'minimax-m2': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'm2-her': { kind: 'chat', capabilities: { tools: true } },
  'minimax-m1': { kind: 'chat', capabilities: { tools: true } },
  'mini-max-text-01': { kind: 'chat', capabilities: { tools: true } },

  // ── Meta Llama ─────────────────────────────────────
  'llama-4-scout-17b-16e': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'llama-4-maverick-17b-128e': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'llama-3.3-70b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'llama-3.2-11b-vision-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'llama-3.2-90b-vision-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'llama-4-maverick': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'llama-4-scout': { kind: 'chat', capabilities: { vision: true, tools: true } },

  // ── Mistral / Mixtral ──────────────────────────────
  'mistral-large-3': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'mistral-medium-3.1': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'mistral-small-4': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'mistral-small-3.2': { kind: 'chat', capabilities: { tools: true } },
  'mistral-large-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'mistral-small-latest': { kind: 'chat', capabilities: { tools: true } },
  'magistral-medium-1.2': { kind: 'chat', capabilities: { vision: true, reasoning: true } },
  'magistral-small-1.2': { kind: 'chat', capabilities: { reasoning: true } },
  'devstral-2': { kind: 'chat', capabilities: { tools: true } },
  'codestral-latest': { kind: 'chat', capabilities: { tools: true } },
  'pixtral-large-latest': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'mixtral-8x7b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'mixtral-8x22b-instruct': { kind: 'chat', capabilities: { tools: true } },

  // ── Moonshot / Kimi ────────────────────────────────
  'kimi-k2.5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'kimi-k2-thinking': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'kimi-k2-thinking-turbo': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'kimi-k2-turbo-preview': { kind: 'chat', capabilities: { tools: true } },
  'kimi-latest': { kind: 'chat', capabilities: { tools: true } },
  'kimi-k2': { kind: 'chat', capabilities: { tools: true } },
  'moonshot-v1-8k': { kind: 'chat' },
  'moonshot-v1-32k': { kind: 'chat' },
  'moonshot-v1-128k': { kind: 'chat' },
  'moonshot-v1-8k-vision-preview': { kind: 'chat', capabilities: { vision: true } },
  'moonshot-v1-32k-vision-preview': { kind: 'chat', capabilities: { vision: true } },
  'moonshot-v1-128k-vision-preview': { kind: 'chat', capabilities: { vision: true } },

  // ── Cohere ─────────────────────────────────────────
  'command-a-03-2025': { kind: 'chat', capabilities: { tools: true } },
  'command-a-vision-07-2025': { kind: 'chat', capabilities: { vision: true } },
  'command-a-reasoning-08-2025': { kind: 'chat', capabilities: { reasoning: true } },
  'command-r7b-12-2024': { kind: 'chat', capabilities: { tools: true } },
  'command-r-plus-08-2024': { kind: 'chat', capabilities: { tools: true } },
  'command-r-08-2024': { kind: 'chat', capabilities: { tools: true } },
  'command-r-plus': { kind: 'chat', capabilities: { tools: true } },
  'command-r': { kind: 'chat', capabilities: { tools: true } },
  'rerank-v3': { kind: 'rerank' },
  'rerank-english-v3': { kind: 'rerank' },
  'embed-v4': { kind: 'embedding' },

  // ── Perplexity ─────────────────────────────────────
  'sonar': { kind: 'chat', capabilities: { webSearch: true } },
  'sonar-pro': { kind: 'chat', capabilities: { webSearch: true } },
  'sonar-reasoning': { kind: 'chat', capabilities: { reasoning: true, webSearch: true } },
  'sonar-reasoning-pro': { kind: 'chat', capabilities: { reasoning: true, webSearch: true } },

  // ── Hunyuan / 腾讯 ─────────────────────────────────
  'tencent-hy-2.0-think': { kind: 'chat', capabilities: { tools: true, reasoning: true, webSearch: true } },
  'tencent-hy-2.0-instruct': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'hunyuan-t1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'hunyuan-turbos': { kind: 'chat', capabilities: { tools: true } },
  'hunyuan-a13b': { kind: 'chat', capabilities: { tools: true } },
  'tencent-hy-vision-1.5-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'hunyuan-turbos-vision': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'hunyuan-t1-vision': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'hunyuan-lite': { kind: 'chat', capabilities: { tools: true } },

  // ── Step / 阶跃星辰 ────────────────────────────────
  'step-3.5-flash': { kind: 'chat', capabilities: { tools: true, reasoning: true, webSearch: true } },
  'step-3': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'step-2-16k': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'step-2-mini': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'step-r1-v-mini': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'step-1o-turbo-vision': { kind: 'chat', capabilities: { vision: true, tools: true } },

  // ── Spark / 星火 ───────────────────────────────────
  'spark-x2': { kind: 'chat', capabilities: { tools: true, reasoning: true, webSearch: true } },
  'spark-ultra': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'spark-max': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'spark-pro': { kind: 'chat', capabilities: { tools: true, webSearch: true } },
  'spark-lite': { kind: 'chat' },
  'spark-4.0-ultra': { kind: 'chat', capabilities: { vision: true, tools: true, webSearch: true } },

  // ── Amazon Nova ────────────────────────────────────
  'amazon-nova-premier-v1:0': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'amazon-nova-pro-v1:0': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'amazon-nova-lite-v1:0': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'amazon-nova-micro-v1:0': { kind: 'chat', capabilities: { tools: true } },
  'amazon-nova-canvas-v1:0': { kind: 'image' },
  'amazon-nova-reel-v1:0': { kind: 'video' },

  // ── Yi / 零一万物 ──────────────────────────────────
  'yi-lightning': { kind: 'chat' },
  'yi-large': { kind: 'chat' },
  'yi-large-turbo': { kind: 'chat' },
  'yi-medium': { kind: 'chat' },
  'yi-medium-200k': { kind: 'chat' },
  'yi-vision': { kind: 'chat', capabilities: { vision: true } },
  'yi-vision-v2': { kind: 'chat', capabilities: { vision: true } },

  // ── SiliconCloud / 硅基流动 ─────────────────────────
  // Source: https://cloud.siliconflow.cn/me/models (2026-04-17)
  // Format: org/model-name or Pro/org/model-name
  // Chat models
  'moonshotai/kimi-k2-instruct-0905': { kind: 'chat', capabilities: { tools: true } },
  'pro/minimaxai/minimax-m2.5': { kind: 'chat', capabilities: { tools: true } },
  'pro/zai-org/glm-5': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/zai-org/glm-5.1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/thudm/glm-4-9b-chat': { kind: 'chat', capabilities: { tools: true } },
  'pro/qwen/qwen2-7b-instruct': { kind: 'chat' },
  'pro/qwen/qwen2.5-coder-7b-instruct': { kind: 'chat' },
  'thudm/glm-4-9b-chat': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2-7b-instruct': { kind: 'chat' },
  'qwen/qwen2.5-coder-7b-instruct': { kind: 'chat' },
  'deepseek-ai/deepseek-vl2': { kind: 'chat', capabilities: { vision: true } },
  'pro/qwen/qwen2.5-vl-7b-instruct': { kind: 'chat', capabilities: { vision: true } },
  'qwen/qwen3-next-80b-a3b-thinking': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-next-80b-a3b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'pro/minimaxai/minimax-m2.1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'moonshotai/kimi-dev-72b': { kind: 'chat', capabilities: { reasoning: true } },
  'paddlepaddle/paddleocr-vl-1.5': { kind: 'chat', capabilities: { vision: true } },
  'pro/deepseek-ai/deepseek-r1-distill-qwen-7b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-r1-distill-qwen-7b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-r1-distill-qwen-14b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-r1-distill-qwen-32b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/moonshotai/kimi-k2.5': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'deepseek-ai/deepseek-v3.2': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'stepfun-ai/step-3.5-flash': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-30b-a3b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'thudm/glm-z1-rumination-32b-0414': { kind: 'chat', capabilities: { reasoning: true } },
  'qwen/qvq-72b-preview': { kind: 'chat', capabilities: { vision: true } },
  'tongyi-zhiwen/qwenlong-l1-32b': { kind: 'chat', capabilities: { reasoning: true } },
  'pro/thudm/glm-4.1v-9b-thinking': { kind: 'chat', capabilities: { vision: true } },
  'minimaxai/minimax-m1-80k': { kind: 'chat', capabilities: { reasoning: true } },
  'minimaxai/minimax-m2': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'stepfun-ai/step3': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'thudm/glm-4.1v-9b-thinking': { kind: 'chat', capabilities: { vision: true } },
  'paddlepaddle/paddleocr-vl': { kind: 'chat', capabilities: { vision: true } },
  'inclusionai/ling-mini-2.0': { kind: 'chat', capabilities: { tools: true } },
  'inclusionai/ling-flash-2.0': { kind: 'chat', capabilities: { tools: true } },
  'inclusionai/ring-flash-2.0': { kind: 'chat', capabilities: { reasoning: true } },
  'deepseek-ai/deepseek-ocr': { kind: 'chat', capabilities: { vision: true } },
  'pro/moonshotai/kimi-k2-instruct-0905': { kind: 'chat', capabilities: { tools: true } },
  'pro/moonshotai/kimi-k2-thinking': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/deepseek-ai/deepseek-v3': { kind: 'chat', capabilities: { tools: true } },
  'pro/deepseek-ai/deepseek-r1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/deepseek-ai/deepseek-v3.1-terminus': { kind: 'chat', capabilities: { tools: true } },
  'pro/deepseek-ai/deepseek-v3.2': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/zai-org/glm-4.7': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'moonshotai/kimi-k2-thinking': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'zai-org/glm-4.6': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'zai-org/glm-4.5': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-8b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-235b-a22b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'zai-org/glm-4.6v': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'teleai/telemm': { kind: 'chat', capabilities: { vision: true } },
  'teleai/telechat2': { kind: 'chat' },
  'qwen/qwen3-vl-32b-thinking': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-vl-32b-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'inclusionai/ling-1t': { kind: 'chat', capabilities: { tools: true } },
  'inclusionai/ring-1t': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-v3.1-terminus': { kind: 'chat', capabilities: { tools: true } },
  'kwaipilot/kat-dev': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen3-vl-8b-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen/qwen3-vl-8b-thinking': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-vl-30b-a3b-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen/qwen3-vl-30b-a3b-thinking': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-vl-235b-a22b-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen/qwen3-vl-235b-a22b-thinking': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-omni-30b-a3b-instruct': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'qwen/qwen3-omni-30b-a3b-thinking': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-omni-30b-a3b-captioner': { kind: 'chat', capabilities: { vision: true, tools: true } },
  'tencent/hunyuan-mt-7b': { kind: 'chat' },
  'deepseek-ai/deepseek-v3': { kind: 'chat', capabilities: { tools: true } },
  'deepseek-ai/deepseek-r1': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-v2.5': { kind: 'chat', capabilities: { tools: true } },
  'deepseek-ai/deepseek-v3.1-0820': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'pro/deepseek-ai/deepseek-v3.1-0820': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'bytedance-seed/seed-oss-36b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'zai-org/glm-4.5v': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3-coder-480b-a35b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen3-coder-30b-a3b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen3-235b-a22b-thinking-2507': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen3-235b-a22b-instruct-2507': { kind: 'chat', capabilities: { tools: true } },
  'zai-org/glm-4.5-air': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-30b-a3b-instruct-2507': { kind: 'chat', capabilities: { tools: true } },
  'moonshotai/kimi-k2-instruct-0711': { kind: 'chat', capabilities: { tools: true } },
  'pro/moonshotai/kimi-k2-instruct-0711': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen3-30b-a3b-thinking-2507': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'tencent/hunyuan-a13b-instruct': { kind: 'chat', capabilities: { reasoning: true } },
  'baidu/ernie-4.5-300b-a47b': { kind: 'chat' },
  'qwen/qwen3-32b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen3-14b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'ascend-tribe/pangu-pro-moe': { kind: 'chat', capabilities: { reasoning: true } },
  'deepseek-ai/deepseek-coder-v2-instruct': { kind: 'chat' },
  'qwen/qwen2-57b-a14b-instruct': { kind: 'chat' },
  'deepseek-ai/deepseek-v2-chat': { kind: 'chat' },
  'tencent/hunyuan-a52b-instruct': { kind: 'chat' },
  'pro/deepseek-ai/deepseek-v3-1226': { kind: 'chat', capabilities: { tools: true } },
  'pro/deepseek-ai/deepseek-r1-0120': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwq-32b-preview': { kind: 'chat' },
  'qwen/qwen2.5-coder-32b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2-1.5b-instruct': { kind: 'chat' },
  'pro/deepseek-ai/deepseek-r1-distill-qwen-1.5b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'deepseek-ai/deepseek-r1-distill-qwen-1.5b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'internlm/internlm2_5-20b-chat': { kind: 'chat', capabilities: { tools: true } },
  'thudm/chatglm3-6b': { kind: 'chat' },
  'pro/qwen/qwen2-vl-7b-instruct': { kind: 'chat', capabilities: { vision: true } },
  'pro/qwen/qwen2-1.5b-instruct': { kind: 'chat' },
  'deepseek-ai/deepseek-r1-0528-qwen3-8b': { kind: 'chat', capabilities: { reasoning: true } },
  'thudm/glm-z1-9b-0414': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'thudm/glm-z1-32b-0414': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwq-32b': { kind: 'chat', capabilities: { tools: true, reasoning: true } },
  'qwen/qwen2.5-7b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2.5-32b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2.5-72b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'vendor-a/qwen/qwen2-72b-instruct': { kind: 'chat' },
  'vendor-a/qwen/qwen2.5-72b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2.5-vl-72b-instruct': { kind: 'chat', capabilities: { vision: true } },
  'qwen/qwen2.5-vl-32b-instruct': { kind: 'chat', capabilities: { vision: true } },
  'thudm/glm-4-9b-0414': { kind: 'chat', capabilities: { tools: true } },
  'thudm/glm-4-32b-0414': { kind: 'chat', capabilities: { tools: true } },
  '01-ai/yi-1.5-6b-chat': { kind: 'chat' },
  '01-ai/yi-1.5-34b-chat-16k': { kind: 'chat' },
  '01-ai/yi-1.5-9b-chat-16k': { kind: 'chat' },
  'pro/01-ai/yi-1.5-6b-chat': { kind: 'chat' },
  'pro/01-ai/yi-1.5-9b-chat-16k': { kind: 'chat' },
  'qwen/qwen1.5-14b-chat': { kind: 'chat' },
  'qwen/qwen1.5-110b-chat': { kind: 'chat' },
  'qwen/qwen1.5-7b-chat': { kind: 'chat' },
  'qwen/qwen1.5-32b-chat': { kind: 'chat' },
  'pro/qwen/qwen1.5-7b-chat': { kind: 'chat' },
  'qwen/qwen2.5-72b-instruct-128k': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2-72b-instruct': { kind: 'chat' },
  'qwen/qwen2.5-math-72b-instruct': { kind: 'chat' },
  'qwen/qwen2.5-14b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'pro/internlm/internlm2_5-7b-chat': { kind: 'chat', capabilities: { tools: true } },
  'pro/thudm/chatglm3-6b': { kind: 'chat' },
  'pro/qwen/qwen2.5-7b-instruct': { kind: 'chat', capabilities: { tools: true } },
  'internlm/internlm2_5-7b-chat': { kind: 'chat', capabilities: { tools: true } },
  'qwen/qwen2-vl-72b-instruct': { kind: 'chat', capabilities: { vision: true } },
  'qwen/qwen2-math-72b-instruct': { kind: 'chat' },
  // Qwen multimodal (原生多模态)
  'qwen/qwen3.5-27b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3.5-122b-a10b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3.5-397b-a17b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3.5-9b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3.5-35b-a3b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  'qwen/qwen3.5-4b': { kind: 'chat', capabilities: { vision: true, tools: true, reasoning: true } },
  // Image models
  'qwen/qwen-image': { kind: 'image' },
  'qwen/qwen-image-edit': { kind: 'image' },
  'qwen/qwen-image-edit-2509': { kind: 'image' },
  'kwai-kolors/kolors': { kind: 'image' },
  // Video models
  'wan-ai/wan2.2-t2v-a14b': { kind: 'video' },
  'wan-ai/wan2.2-i2v-a14b': { kind: 'video' },
  'wan-ai/wan2.1-i2v-14b-720p-turbo': { kind: 'video' },
  'wan-ai/wan2.1-i2v-14b-720p': { kind: 'video' },
  'wan-ai/wan2.1-t2v-14b-turbo': { kind: 'video' },
  'wan-ai/wan2.1-t2v-14b': { kind: 'video' },
  'tencent/hunyuanvideo-hd': { kind: 'video' },
  'tencent/hunyuanvideo': { kind: 'video' },
  // Audio models
  'teleai/telespeechasr': { kind: 'audio' },
  'funaudiollm/sensevoicesmall': { kind: 'audio' },
  'funaudiollm/cosyvoice2-0.5b': { kind: 'audio' },
  'indexteam/indextts-2': { kind: 'audio' },
  'fnlp/moss-ttsd-v0.5': { kind: 'audio' },
  // Embedding models
  'qwen/qwen3-embedding-4b': { kind: 'embedding' },
  'qwen/qwen3-embedding-8b': { kind: 'embedding' },
  'qwen/qwen3-embedding-0.6b': { kind: 'embedding' },
  'netease-youdao/bce-embedding-base_v1': { kind: 'embedding' },
  'baai/bge-m3': { kind: 'embedding' },
  'pro/baai/bge-m3': { kind: 'embedding' },
  'baai/bge-large-zh-v1.5': { kind: 'embedding' },
  'baai/bge-large-en-v1.5': { kind: 'embedding' },
  // Reranker models
  'qwen/qwen3-reranker-8b': { kind: 'rerank' },
  'qwen/qwen3-reranker-0.6b': { kind: 'rerank' },
  'qwen/qwen3-reranker-4b': { kind: 'rerank' },
  'netease-youdao/bce-reranker-base_v1': { kind: 'rerank' },
  'baai/bge-reranker-v2-m3': { kind: 'rerank' },
  'pro/baai/bge-reranker-v2-m3': { kind: 'rerank' },
};

/** Suffixes to strip for fuzzy matching */
const STRIP_SUFFIXES = [
  /-latest$/, /:free$/, /-preview$/, /-chat$/, /-instruct$/,
  /-202\d-\d{2}-\d{2}$/, /-\d{8}$/, /-v\d+(\.\d+)*$/,
];

/**
 * Look up model kind and capabilities from the hardcoded registry.
 * Tries exact match first, then strips common suffixes.
 */
export function resolveFromRegistry(modelId: string): RegistryEntry | undefined {
  const lower = modelId.toLowerCase();

  // Exact match
  if (REGISTRY[lower]) {
    return REGISTRY[lower];
  }

  // Strip suffixes and retry
  let candidate = lower;
  for (const suffix of STRIP_SUFFIXES) {
    const stripped = candidate.replace(suffix, '');
    if (stripped !== candidate) {
      if (REGISTRY[stripped]) {
        return REGISTRY[stripped];
      }
      candidate = stripped;
      break;
    }
  }

  return undefined;
}
